services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fcg-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=FcgPassword@123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - fcg-network

  api:
    build:
      context: ./src
      dockerfile: FCG.API/Dockerfile
    container_name: fcg-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ConnectionStrings__FCG=Server=sqlserver;Database=FiapCloudGames;User Id=sa;Password=FcgPassword@123;TrustServerCertificate=True
      - Jwt__Key=cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
      - IdentitySeedAdmin__Email=admin@fcg.com
      - IdentitySeedAdmin__Password=Admin123!
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    networks:
      - fcg-network
    restart: on-failure

volumes:
  sql_data:

networks:
  fcg-network:
    driver: bridge